[project]
name = "vercel-fastapi-starter"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi[standard]>=0.121.0",
  "psycopg2-binary>=2.9.11",
  "sqlalchemy>=2.0.45",
  "supabase>=2.27.2",
  "uvicorn>=0.34.0",
]
